In [81]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [82]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
test["loss"]=np.nan

In [90]:
train.describe()

id          cont1          cont2          cont3  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean   294135.982561       0.493861       0.507188       0.498918   
std    169336.084867       0.187640       0.207202       0.202105   
min         1.000000       0.000016       0.001149       0.002634   
25%    147748.250000       0.346090       0.358319       0.336963   
50%    294539.500000       0.475784       0.555782       0.527991   
75%    440680.500000       0.623912       0.681761       0.634224   
max    587633.000000       0.984975       0.862654       0.944251   

               cont4          cont5          cont6          cont7  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean        0.491812       0.487428       0.490945       0.484970   
std         0.211292       0.209027       0.205273       0.178450   
min         0.176921       0.281143       0.012683       0.069503   
25%         0.327354       0.281143       0.336105       0.350175   
50%         0.452887       0.422268       0.440945       0.438285   
75%         0.652072       0.643315       0.655021       0.591045   
max         0.954297       0.983674       0.997162       1.000000   

               cont8          cont9         cont10         cont11  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean        0.486437       0.485506       0.498066       0.493511   
std         0.199370       0.181660       0.185877       0.209737   
min         0.236880       0.000080       0.000000       0.035321   
25%         0.312800       0.358970       0.364580       0.310961   
50%         0.441060       0.441450       0.461190       0.457203   
75%         0.623580       0.566820       0.614590       0.678924   
max         0.980200       0.995400       0.994980       0.998742   

              cont12         cont13         cont14           loss  
count  188318.000000  188318.000000  188318.000000  188318.000000  
mean        0.493150       0.493138       0.495717    3037.337686  
std         0.209427       0.212777       0.222488    2904.086186  
min         0.036232       0.000228       0.179722       0.670000  
25%         0.311661       0.315758       0.294610    1204.460000  
50%         0.462286       0.363547       0.407403    2115.570000  
75%         0.675759       0.689974       0.724623    3864.045000  
max         0.998484       0.988494       0.844848  121012.250000

In [91]:
test.describe()

id          cont1          cont2          cont3  \
count  125546.000000  125546.000000  125546.000000  125546.000000   
mean   294067.153442       0.494447       0.506939       0.498255   
std    170098.335649       0.187961       0.206837       0.201746   
min         4.000000       0.000016       0.001149       0.002634   
25%    146414.250000       0.347403       0.358319       0.336963   
50%    294306.000000       0.475784       0.555782       0.527991   
75%    441800.000000       0.626630       0.681761       0.634224   
max    587634.000000       0.984975       0.862654       0.944251   

               cont4          cont5          cont6          cont7  \
count  125546.000000  125546.000000  125546.000000  125546.000000   
mean        0.492334       0.487640       0.492188       0.485945   
std         0.210815       0.209119       0.205574       0.178650   
min         0.176921       0.281143       0.012683       0.069503   
25%         0.327354       0.281143       0.336105       0.352087   
50%         0.452887       0.422268       0.441525       0.438893   
75%         0.652072       0.643315       0.659261       0.591284   
max         0.956046       0.983107       0.997162       1.000000   

               cont8          cont9         cont10         cont11  \
count  125546.000000  125546.000000  125546.000000  125546.000000   
mean        0.487401       0.486015       0.498909       0.494360   
std         0.199549       0.182134       0.185950       0.210399   
min         0.236880       0.000080       0.000000       0.035321   
25%         0.317960       0.358970       0.364580       0.310961   
50%         0.441060       0.441450       0.466720       0.457203   
75%         0.629180       0.568890       0.619840       0.678924   
max         0.982800       0.995400       0.994980       0.997830   

              cont12         cont13         cont14  loss  
count  125546.000000  125546.000000  125546.000000   0.0  
mean        0.494033       0.495086       0.495586   NaN  
std         0.210148       0.213108       0.222613   NaN  
min         0.036232       0.000228       0.178568   NaN  
25%         0.318249       0.315758       0.294752   NaN  
50%         0.462286       0.363547       0.406104   NaN  
75%         0.682413       0.689974       0.724791   NaN  
max         0.997416       0.988494       0.844814   NaN

In [92]:
train.shape

(188318, 132)

In [93]:
train.tail()

id cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9   ...     \
188313  587620    A    B    A    A    A    A    A    A    B   ...      
188314  587624    A    A    A    A    A    B    A    A    A   ...      
188315  587630    A    B    A    A    A    A    A    B    B   ...      
188316  587632    A    B    A    A    A    A    A    A    B   ...      
188317  587633    B    A    A    B    A    A    A    A    A   ...      

           cont6     cont7    cont8    cont9   cont10    cont11    cont12  \
188313  0.242437  0.289949  0.24564  0.30859  0.32935  0.223038  0.220003   
188314  0.334270  0.382000  0.63475  0.40455  0.47779  0.307628  0.301921   
188315  0.345883  0.370534  0.24564  0.45808  0.47779  0.445614  0.443374   
188316  0.704364  0.562866  0.34987  0.44767  0.53881  0.863052  0.852865   
188317  0.844563  0.533048  0.97123  0.93383  0.83814  0.932195  0.946432   

          cont13    cont14     loss  
188313  0.333292  0.208216  1198.62  
188314  0.318646  0.305872  1108.34  
188315  0.339244  0.503888  5762.64  
188316  0.654753  0.721707  1562.87  
188317  0.810511  0.721460  4751.72  

[5 rows x 132 columns]

In [94]:
test.head()

id cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9 ...      cont6     cont7  \
0   4    A    B    A    A    A    A    A    A    B ...   0.466591  0.317681   
1   6    A    B    A    B    A    A    A    A    B ...   0.482425  0.443760   
2   9    A    B    A    B    B    A    B    A    B ...   0.212308  0.325779   
3  12    A    A    A    A    B    A    A    A    A ...   0.369930  0.342355   
4  15    B    A    A    A    A    B    A    A    A ...   0.398862  0.391833   

     cont8    cont9   cont10    cont11    cont12    cont13    cont14 loss  
0  0.61229  0.34365  0.38016  0.377724  0.369858  0.704052  0.392562  NaN  
1  0.71330  0.51890  0.60401  0.689039  0.675759  0.453468  0.208045  NaN  
2  0.29758  0.34365  0.30529  0.245410  0.241676  0.258586  0.297232  NaN  
3  0.40028  0.33237  0.31480  0.348867  0.341872  0.592264  0.555955  NaN  
4  0.23688  0.43731  0.50556  0.359572  0.352251  0.301535  0.825823  NaN  

[5 rows x 132 columns]

In [95]:
data = pd.concat([train,test], axis = 0, join = 'outer', ignore_index = True)

In [96]:
col = list(data.columns)
col = col[1:]

In [97]:
col.append("id")

In [98]:
data = data[col]

In [99]:
data.head()

cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9 cat10 ...     cont7    cont8  \
0    A    B    A    B    A    A    A    A    B     A ...  0.335060  0.30260   
1    A    B    A    A    A    A    A    A    B     B ...  0.436585  0.60087   
2    A    B    A    A    B    A    A    A    B     B ...  0.315545  0.27320   
3    B    B    A    B    A    A    A    A    B     A ...  0.391128  0.31796   
4    A    B    A    B    A    A    A    A    B     B ...  0.247408  0.24564   

     cont9   cont10    cont11    cont12    cont13    cont14     loss  id  
0  0.67135  0.83510  0.569745  0.594646  0.822493  0.714843  2213.18   1  
1  0.35127  0.43919  0.338312  0.366307  0.611431  0.304496  1283.60   2  
2  0.26076  0.32446  0.381398  0.373424  0.195709  0.774425  3005.09   5  
3  0.32128  0.44467  0.327915  0.321570  0.605077  0.602642   939.85  10  
4  0.22089  0.21230  0.204687  0.202213  0.246011  0.432606  2763.85  11  

[5 rows x 132 columns]

In [100]:
labelencoder = LabelEncoder()
codecol = data.ix[:,"cat1":"cat116"].apply(lambda x: labelencoder.fit_transform(x))

C:\Users\leiwen\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [101]:
onehotencoder = OneHotEncoder()

In [102]:
codecol= onehotencoder.fit_transform(codecol).toarray()

In [103]:
type(codecol)

numpy.ndarray

In [104]:
num = data.ix[:,"cont1":].values

In [105]:
data= np.hstack((codecol,num))

In [106]:
data.shape

(313864, 1192)

In [107]:
train = data[0:188318]

In [108]:
test = data[188318:]

In [109]:
test[:,-1] = test[:,-1].astype("int")

In [110]:
from sklearn.linear_model import LinearRegression

In [111]:
train[0,-2]

2213.1799999999998

In [118]:
train[:,-1]

array([  1.00000000e+00,   2.00000000e+00,   5.00000000e+00, ...,
         5.87630000e+05,   5.87632000e+05,   5.87633000e+05])

In [119]:
X = train[:,0:-2]

In [120]:
Y  = train[:,-2]

In [121]:
regressor = LinearRegression()
regressor.fit(X, Y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [122]:
test[:,-2]

array([  1133. ,   2071.5,  11253.5, ...,   3248.5,    948.5,   4701. ])

In [123]:
test[:,-2] = regressor.predict(test[:,0:-2])

In [124]:
test[:,-2]

array([  1133. ,   2071.5,  11253.5, ...,   3248.5,    948.5,   4701. ])

In [125]:
pred =pd.DataFrame(test[:,-2:],columns = ["loss","id"])

In [126]:
pred = pred[["id","loss"]]

In [127]:
pred["id"] = pred["id"].astype("int")

In [128]:
pred.describeribe()

id          loss
count  125546.000000  1.255460e+05
mean   294067.153442 -3.016591e+09
std    170098.335649  5.335986e+12
min         4.000000 -9.840469e+14
25%    146414.250000  1.623500e+03
50%    294306.000000  2.543000e+03
75%    441800.000000  3.915500e+03
max    587634.000000  6.896529e+14

In [129]:
def smooth(x):
    if x>121012.250000 :
        x = 121012.250000
    elif x<0:
        x = 0
    return x

In [131]:
pred["loss"]=pred["loss"].apply(lambda x:smooth(x))

In [133]:
pred.to_csv("pred.csv",index= False)